# Site settings
title: Asociacion Robotech
email: robotechurjc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "robotech.github.io" # the base hostname & protocol for your site

twitter_username: robotech_urjc
github_username: RoboTech-URJC

# Build settings
markdown: kramdown
